### ISSUE TITLE
Wheels and Tracks not compatible with TweakScale

### ISSUE THREAD

**Issue by WolfairCorp** [shadowmage45/KSPWheel#4] opened 2016-11-29 12:54 UTC
Minor Issue : When tweakscaling parts, colliders (I think) keep the original size, resulting in bouncing everywhere. Also, the part highlighting is wrong when TweakScaled.
![screenshot632](https://cloud.githubusercontent.com/assets/23337309/20710533/e9b6e096-b608-11e6-9168-93f25cb11abf.png)
![screenshot621](https://cloud.githubusercontent.com/assets/23337309/20710538/f39b7eaa-b608-11e6-9a29-5230b967b931.png)
![screenshot624](https://cloud.githubusercontent.com/assets/23337309/20710544/fcfe8410-b608-11e6-8a64-8b5672db2d84.png)
[output_log.txt](https://github.com/shadowmage45/KSPWheel/files/618985/output_log.txt)

**Comment by shadowmage45** [comment] 2016-11-29 16:09
Noted; thanks for the report.

I don't normally use TweakScale, so no support is currently included.  I will see what I can do to add support, at least at the model/geometry/size level;  supporting scaling of the actual wheel settings (load mostly) will be a bit more difficult to figure out.

**Comment by shadowmage45** [comment] 2016-11-29 19:19
![screenshot4](https://cloud.githubusercontent.com/assets/1503399/20725094/01236252-b62e-11e6-9266-c300b5618f50.png)

Mostly functional now; though some of the wheels are -extremely- sensitive at small scales.

Should be available with the next release.

**Comment by shadowmage45** [comment] 2016-11-29 19:20
On the highlighting -- I'm not seeing anything wrong?  What specifically is wrong with the highlighting?

**Comment by WolfairCorp** [comment] 2016-11-29 21:14
You cannot see the cursor, but it is in the middle of nowhere (where the part is if it wasn't rescaled) .
![git](https://cloud.githubusercontent.com/assets/23337309/20729251/2f7e32b4-b64f-11e6-9e79-03131b8abcf9.png)

**Comment by shadowmage45** [comment] 2016-11-29 21:45
Ahh, thanks for the reply;  that too should be fixed with the latest release.  Was caused by some incorrectly scaled colliders, which should now be scaled properly along with everything else.

**Comment by shadowmage45** [comment] 2016-11-29 22:23
Working on fixing up the stock wheels that use 'rescaleFactor' in their config; would probably be good to support that setting anyway.  Though will require rescaling the config values in use on those parts, it should allow for greater general compatibility.

**Comment by shadowmage45** [comment] 2016-11-30 00:15
Rescale factor is now supported and should be available in the next build.  Cleans up a few other misc issues with parts using it as well, things that previously left me a bit stumped.

**Comment by shadowmage45** [comment] 2016-12-03 19:15
Basic tweakscale support should now be complete.

Investigating the best scaling methods for load rating, wheel mass, and motor/brake torques, as well as how to scale the torque and steering curves.

**Comment by shadowmage45** [comment] 2016-12-10 18:24
PartModule problem, no longer supported.

**Closed as completed by shadowmage45** 2016-12-10 18:24 UTC
