### ISSUE TITLE
NullReferenceSpam with KSPWheel

### ISSUE THREAD

**Issue by tivec** [shadowmage45/KSPWheel#56] opened 2018-04-05 13:35 UTC
I literally have a few hundred thousands of this in my log, using KSPWheel version 0.11.8.26. I'd attach the full log, but it's unfortunately over 600mb :D

I have monitored it and it starts immediately as you load up the craft on the runway, and continues even after you have taken off.

```(Filename:  Line: -1)

Exception handling event onFloatingOriginShift in class KSPWheelDustEffects:System.NullReferenceException: Object reference not set to an instance of an object
  at KSPWheel.KSPWheelDustEffects.onOriginShift (Vector3d o, Vector3d n) [0x00000] in <filename unknown>:0 
  at EventData`2[Vector3d,Vector3d].Fire (Vector3d data0, Vector3d data1) [0x00000] in <filename unknown>:0 
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at KSPWheel.KSPWheelDustEffects.onOriginShift (Vector3d o, Vector3d n) [0x00000] in <filename unknown>:0 
  at EventData`2[Vector3d,Vector3d].Fire (Vector3d data0, Vector3d data1) [0x00000] in <filename unknown>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
EventData`2:Fire(Vector3d, Vector3d)
FloatingOrigin:setOffset(Vector3d, Vector3d)
FloatingOrigin:FixedUpdate()
```

**Comment by shadowmage45** [comment] 2018-04-05 15:58
Thanks for the report.

This would point towards there being an error in one of the dust-effect related updating methods.  Not surprising, as I wasn't able to test that specific function in the time I had available.

If you would like to stop the log-spam temporarily, you should be able to disable the dust-effects from the in-game difficulty menu (mod settings->kspwheel->dust effects).  Note that this will also disable the entire dust system.

Should be able to implement a fix for this when next I have some free development time.

**Comment by tivec** [comment] 2018-04-05 15:59
Ok, I wasn't aware there were settings for it in there, I'll use that. I had downgraded KSPWheel and KerbalFoundries to the 1.4.1 version and it's been running well (even on 1.4.2).

**Comment by shadowmage45** [comment] 2018-04-05 23:43
I'm unable to duplicate this problem using the KSP 1.4.2 public release ( https://github.com/shadowmage45/KSPWheel/releases/tag/0.11.8.26 ).

Am able to launch a craft, drive around KSC, take-off, land many KM away, drive for several KM on the ground, all without any log-spam or null-refs.

![screenshot9](https://user-images.githubusercontent.com/1503399/38397007-7e5875fc-38f8-11e8-8ee7-950767611349.png)

Would you be able to provide a log file, and/or more information about how to reproduce the problem?

**Comment by RaccoonTOF** [comment] 2018-04-07 08:04
Can't really add any more information on how to reproduce, but I can confirm that it does happen - however, it also seems to happen sporadically, even with the same craft.  It's fairly easy to tell in game when it occurs - immediately after liftoff the game starts stuttering and micro-freezing regularly, while when it is not throwing the exception it runs perfectly smoothly.  I'll try to get a log next time it occurs, but as tivec commented above, it RAPIDLY fills the log when it does happen - his snippet there is pretty much just repeated thousands of times.  Would a more condensed version of the log be useful, and if so, which part(s)?

**Comment by RaccoonTOF** [comment] 2018-04-07 09:11
Well, got a log - 58MB in size.  It's got some other issues with Texture Replacer Replaced as well bloating the file size (which I hadn't noticed before, but appears to be a separate issue).  

https://www.dropbox.com/s/bp9luh6lzfh64wo/KSP_dusteffectsbroken.log?dl=0

**Comment by RaccoonTOF** [comment] 2018-04-07 18:56
Just an update to verify that it still happens after removing TRR entirely.

**Comment by RaccoonTOF** [comment] 2018-04-07 22:39
Disabling dust effects also does not reliably stop the log messages.  Even with the entire dust effect system disabled in the save, exiting KSP, reloading, verifying that the dust effects were still disabled, and then launching an affected craft, I still got over 3GB of errors into the log file in a roughly half hour flight.  Note: swapping away from and back to the affected craft via the tracking station once in orbit SOMETIMES stops the log spam - but not always.  Then again, the errors don't crop up reliably even on the same craft...

**Comment by shadowmage45** [comment] 2018-04-09 15:00
Interesting -- strange that the issue pops up so inconsistently.

If I can find out how to trigger it reliably, I can find out the cause, and then a solution.  Until then... its all just guessing.

**Comment by shadowmage45** [comment] 2018-04-10 00:45
Have finally been able to reproduce the problem, and am starting investigations as to the cause.  Will update with more information when it is known.

**Comment by shadowmage45** [comment] 2018-04-10 01:09
Apparently this is being caused by inactive vessels (loaded but out of physics range) in the flight-scene still receiving 'onOriginShift' event callbacks.

Have updated the code to check to ensure that setup has been run in the onOriginShift event method, so it will no longer error out/spam the log on inactive vessels.  Will do more testing to confirm, and this fix should be available with the next update (soon).

**Comment by RaccoonTOF** [comment] 2018-04-10 08:31
Excellent news, glad you were able to get it tracked down.  It was definitely a head-scratcher for me, just trying to reliably reproduce it to get a log :)

**Closed as completed** 2018-04-10 23:20 UTC
